import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import templateRenderer from '../../services/design/templateRenderer.js';

const prisma = new PrismaClient();
const router = Router();

/**
 * Auto-generate design assets for layout sections
 * Called after layout is saved
 */
async function autoGenerateDesigns(layout) {
  if (!process.env.CANVA_API_KEY) {
    console.log('⚠️  Canva API not configured, skipping auto-generation');
    return;
  }

  // Process each section
  for (const section of layout.sections || []) {
    try {
      // Generate hero banner for hero sections
      if (section.type === 'hero' && section.heroSection) {
        const heroData = {
          headline: section.heroSection.headline,
          subheadline: section.heroSection.subheadline,
          ctaText: section.heroSection.ctaText,
          ctaLink: section.heroSection.ctaLink,
          backgroundColor: section.heroSection.backgroundColor,
          backgroundGradient: section.heroSection.backgroundGradient,
          backgroundImage: section.heroSection.backgroundImage,
        };

        try {
          const result = await templateRenderer.renderHero(heroData);
          if (result.imageUrl) {
            await prisma.heroSection.update({
              where: { sectionId: section.id },
              data: { backgroundImage: result.imageUrl },
            });
          }
        } catch (error) {
          console.warn(`Failed to auto-generate hero for section ${section.id}:`, error.message);
        }
      }

      // Generate bundle graphics for bundle entries
      if (section.type === 'bundle' && section.bundleEntries) {
        for (const entry of section.bundleEntries) {
          if (entry.bundleId) {
            try {
              const bundle = await prisma.productBundle.findUnique({
                where: { id: entry.bundleId },
                include: {
                  products: {
                    include: {
                      images: { orderBy: { sort_order: 'asc' }, take: 1 },
                    },
                  },
                },
              });

              if (bundle) {
                const result = await templateRenderer.renderBundle({
                  name: bundle.name,
                  description: bundle.description,
                  price: bundle.price,
                  discount: bundle.discountPercent,
                  badgeText: bundle.badgeText,
                  badgeColor: bundle.badgeColor,
                  products: bundle.products.map((p) => ({
                    imageUrl: p.images[0]?.image_url || p.imageUrl,
                  })),
                });

                if (result.imageUrl) {
                  await prisma.bundleSectionEntry.update({
                    where: { id: entry.id },
                    data: { imageUrl: result.imageUrl },
                  });
                }
              }
            } catch (error) {
              console.warn(`Failed to auto-generate bundle for entry ${entry.id}:`, error.message);
            }
          }
        }
      }

      // Generate brand row for brand entries
      if (section.type === 'brand_row' && section.bundleEntries) {
        for (const entry of section.bundleEntries) {
          if (entry.brandId) {
            try {
              const brand = await prisma.brand.findUnique({
                where: { id: entry.brandId },
                include: {
                  _count: { select: { products: true } },
                },
              });

              if (brand) {
                const result = await templateRenderer.renderBrandRow({
                  brandName: brand.name,
                  brandLogo: brand.logoUrl,
                  description: brand.description,
                  productCount: brand._count.products,
                });

                if (result.imageUrl) {
                  await prisma.bundleSectionEntry.update({
                    where: { id: entry.id },
                    data: { imageUrl: result.imageUrl },
                  });
                }
              }
            } catch (error) {
              console.warn(`Failed to auto-generate brand row for entry ${entry.id}:`, error.message);
            }
          }
        }
      }
    } catch (error) {
      console.warn(`Failed to process section ${section.id} for auto-generation:`, error.message);
    }
  }
}

// GET /api/catalog/layout - Get front page layout with optimized query
router.get('/', async (req, res) => {
  try {
    const { name = 'default', active = 'true' } = req.query;

    // Check if FrontPageLayout model exists (may not be migrated yet)
    let layout;
    try {
      layout = await prisma.frontPageLayout.findFirst({
        where: {
          name,
          active: active === 'true',
        },
        include: {
          sections: {
            where: { active: true },
            include: {
              heroSection: true,
              bundleEntries: {
                where: { active: true },
                include: {
                  bundle: {
                    include: {
                      products: {
                        where: { isHidden: false, inStock: true },
                        include: {
                          images: {
                            orderBy: { sort_order: 'asc' },
                            take: 1,
                          },
                          category: {
                            select: { id: true, name: true, slug: true },
                          },
                          brand: {
                            select: { id: true, name: true, logoUrl: true },
                          },
                        },
                      },
                    },
                  },
                  product: {
                    include: {
                      images: {
                        orderBy: { sort_order: 'asc' },
                        take: 1,
                      },
                      category: {
                        select: { id: true, name: true, slug: true },
                      },
                      brand: {
                        select: { id: true, name: true, logoUrl: true },
                      },
                    },
                  },
                  category: {
                    include: {
                      _count: {
                        select: { products: true },
                      },
                    },
                  },
                  brand: {
                    include: {
                      _count: {
                        select: { products: true },
                      },
                    },
                  },
                },
                orderBy: { displayOrder: 'asc' },
              },
            },
            orderBy: { displayOrder: 'asc' },
          },
        },
      });
    } catch (error) {
      // Model may not exist yet - return empty layout
      if (error.code === 'P2001' || error.message?.includes('does not exist')) {
        return res.json({
          layout: null,
          message: 'Layout model not migrated yet',
        });
      }
      throw error;
    }

    if (!layout) {
      return res.status(404).json({ 
        error: 'NOT_FOUND',
        message: `Layout "${name}" not found`,
      });
    }

    res.json({ layout });
  } catch (error) {
    console.error('Failed to fetch layout:', error);
    res.status(500).json({ 
      error: 'DATABASE_ERROR',
      message: 'Failed to fetch layout',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
});

// POST /api/catalog/layout - Create or update layout
router.post('/', async (req, res) => {
  try {
    const { name, description, active = true, config, sections } = req.body ?? {};

    // Validation
    if (!name || typeof name !== 'string' || name.trim().length === 0) {
      return res.status(400).json({ 
        error: 'VALIDATION_ERROR',
        message: 'Name is required and must be a non-empty string',
        field: 'name',
      });
    }

    // Check if FrontPageLayout model exists
    try {
      const existing = await prisma.frontPageLayout.findUnique({
        where: { name },
      });

      let layout;
      if (existing) {
        // Update existing layout
        layout = await prisma.frontPageLayout.update({
          where: { name },
          data: {
            description,
            active: Boolean(active),
            config: config || {},
          },
          include: {
            sections: {
              include: {
                heroSection: true,
                bundleEntries: true,
              },
            },
          },
        });
      } else {
        // Create new layout
        layout = await prisma.frontPageLayout.create({
          data: {
            name: name.trim(),
            description: description?.trim() || null,
            active: Boolean(active),
            config: config || {},
            sections: sections
              ? {
                  create: sections.map((section, index) => ({
                    type: section.type || 'products',
                    displayOrder: section.displayOrder ?? index,
                    title: section.title,
                    subtitle: section.subtitle,
                    config: section.config || {},
                    active: section.active ?? true,
                    heroSection: section.type === 'hero' && section.heroSection
                      ? {
                          create: {
                            headline: section.heroSection.headline,
                            subheadline: section.heroSection.subheadline,
                            ctaText: section.heroSection.ctaText,
                            ctaLink: section.heroSection.ctaLink,
                            backgroundImage: section.heroSection.backgroundImage,
                            backgroundColor: section.heroSection.backgroundColor,
                            backgroundGradient: section.heroSection.backgroundGradient,
                            config: section.heroSection.config || {},
                          },
                        }
                      : undefined,
                    bundleEntries: section.bundleEntries
                      ? {
                          create: section.bundleEntries.map((entry, entryIndex) => ({
                            bundleId: entry.bundleId,
                            productId: entry.productId,
                            categoryId: entry.categoryId,
                            brandId: entry.brandId,
                            displayOrder: entry.displayOrder ?? entryIndex,
                            title: entry.title,
                            subtitle: entry.subtitle,
                            imageUrl: entry.imageUrl,
                            config: entry.config || {},
                            active: entry.active ?? true,
                          })),
                        }
                      : undefined,
                  })),
                }
              : undefined,
          },
          include: {
            sections: {
              include: {
                heroSection: true,
                bundleEntries: true,
              },
            },
          },
        });
      }

      // Auto-generate designs for sections (non-blocking)
      autoGenerateDesigns(layout).catch((error) => {
        console.warn('Auto-generation failed (non-critical):', error.message);
      });

      res.status(existing ? 200 : 201).json({ layout });
    } catch (error) {
      // Model may not exist yet
      if (error.code === 'P2001' || error.message?.includes('does not exist')) {
        return res.status(503).json({ 
          error: 'MODEL_NOT_MIGRATED',
          message: 'Layout model not migrated yet. Please run migrations first.',
        });
      }
      throw error;
    }
  } catch (error) {
    console.error('Failed to create/update layout:', error);
    
    if (error.code === 'P2002') {
      return res.status(409).json({ 
        error: 'DUPLICATE_ENTRY',
        message: 'Layout with this name already exists',
        field: 'name',
      });
    }

    res.status(500).json({ 
      error: 'DATABASE_ERROR',
      message: 'Failed to create/update layout',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
});

export default router;

