import { Product, Category } from '../types';

export const brands = {
  lamolienda: {
    id: 'lamolienda',
    name: 'La Molienda',
    color: '#D32F2F',
    secondaryColor: '#F44336',
    logo: 'https://images.pexels.com/photos/1002543/pexels-photo-1002543.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Premium Mexican baked goods and snacks',
  },
  marinela: {
    id: 'marinela',
    name: 'Marinela',
    color: '#1976D2',
    secondaryColor: '#2196F3',
    logo: 'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Sweet treats and bakery favorites',
  },
};

export const rackBundles = [
  {
    id: 'lamolienda-starter',
    brandId: 'lamolienda',
    name: 'La Molienda Display Rack Bundle',
    description: 'Complete starter kit with premium display rack + best-selling products',
    totalValue: 450,
    discountedPrice: 349,
    savings: 101,
    includes: ['Premium 5-tier display rack', '24 Churros mix', '24 Conchas', '12 Pan Dulce variety'],
    rackImage: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'marinela-premium',
    brandId: 'marinela',
    name: 'Marinela Premium Rack Package',
    description: 'Eye-catching display with top-selling sweet treats',
    totalValue: 520,
    discountedPrice: 399,
    savings: 121,
    includes: ['Deluxe 6-tier display rack', '36 Gansitos', '36 Príncipe cookies', '24 Roles'],
    rackImage: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const categories: Category[] = [
  { id: 'all', name: 'All Products' },
  { id: 'bakery', name: 'Bakery' },
  { id: 'snacks', name: 'Snacks' },
  { id: 'beverages', name: 'Beverages' },
  { id: 'bundles', name: 'Rack Bundles' },
  { id: 'specials', name: 'Weekly Specials' },
];

export const products: Product[] = [
  {
    id: 'lm-churros',
    name: 'La Molienda Churros Mix',
    sku: 'LM-CHR-001',
    description: 'Authentic churros mix - makes 24 servings',
    price: 32.99,
    cost: 24.00,
    margin: 27,
    imageUrl: 'https://images.pexels.com/photos/4686958/pexels-photo-4686958.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 450,
    minStock: 100,
    supplier: 'La Molienda',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#FFE5E5',
    categoryId: 'bakery',
    brandId: 'lamolienda',
  },
  {
    id: 'lm-conchas',
    name: 'La Molienda Conchas',
    sku: 'LM-CON-001',
    description: 'Traditional sweet bread shells',
    price: 38.99,
    cost: 28.00,
    margin: 28,
    imageUrl: 'https://images.pexels.com/photos/4686960/pexels-photo-4686960.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 380,
    minStock: 80,
    supplier: 'La Molienda',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#FFF3E0',
    categoryId: 'bakery',
    brandId: 'lamolienda',
  },
  {
    id: 'lm-pandulce',
    name: 'La Molienda Pan Dulce Variety',
    sku: 'LM-PAN-001',
    description: 'Assorted sweet breads - customer favorite',
    price: 42.99,
    cost: 32.00,
    margin: 26,
    imageUrl: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 320,
    minStock: 60,
    supplier: 'La Molienda',
    featured: true,
    unitType: 'case',
    unitsPerCase: 12,
    minOrderQty: 1,
    backgroundColor: '#FFEBEE',
    categoryId: 'bakery',
    brandId: 'lamolienda',
  },
  {
    id: 'mar-gansitos',
    name: 'Marinela Gansitos',
    sku: 'MAR-GAN-001',
    description: 'Chocolate covered snack cakes',
    price: 44.99,
    cost: 34.00,
    margin: 24,
    imageUrl: 'https://images.pexels.com/photos/3026810/pexels-photo-3026810.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 500,
    minStock: 100,
    supplier: 'Marinela',
    featured: true,
    unitType: 'case',
    unitsPerCase: 36,
    minOrderQty: 1,
    backgroundColor: '#E3F2FD',
    categoryId: 'snacks',
    brandId: 'marinela',
  },
  {
    id: 'mar-principe',
    name: 'Marinela Príncipe Cookies',
    sku: 'MAR-PRI-001',
    description: 'Chocolate sandwich cookies',
    price: 39.99,
    cost: 30.00,
    margin: 25,
    imageUrl: 'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 420,
    minStock: 90,
    supplier: 'Marinela',
    featured: true,
    unitType: 'case',
    unitsPerCase: 36,
    minOrderQty: 1,
    backgroundColor: '#BBDEFB',
    categoryId: 'snacks',
    brandId: 'marinela',
  },
  {
    id: 'mar-roles',
    name: 'Marinela Roles',
    sku: 'MAR-ROL-001',
    description: 'Sweet rolls with guava filling',
    price: 36.99,
    cost: 27.00,
    margin: 27,
    imageUrl: 'https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 360,
    minStock: 75,
    supplier: 'Marinela',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#E1F5FE',
    categoryId: 'snacks',
    brandId: 'marinela',
  },
  {
    id: 'coca-cola',
    name: 'Coca-Cola Classic 12oz',
    sku: 'COK-001',
    description: 'Classic Coca-Cola in 12oz cans',
    price: 24.99,
    cost: 18.00,
    margin: 28,
    imageUrl: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 800,
    minStock: 150,
    supplier: 'Coca-Cola Co.',
    featured: false,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 2,
    backgroundColor: '#FFCDD2',
    categoryId: 'beverages',
  },
  {
    id: 'jarritos',
    name: 'Jarritos Variety Pack',
    sku: 'JAR-001',
    description: 'Assorted Mexican sodas',
    price: 28.99,
    cost: 21.00,
    margin: 27,
    imageUrl: 'https://images.pexels.com/photos/2775860/pexels-photo-2775860.jpeg?auto=compress&cs=tinysrgb&w=400',
    inStock: true,
    stock: 340,
    minStock: 70,
    supplier: 'Novamex',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#FFF9C4',
    categoryId: 'beverages',
  },
];

export const weeklySpecials = [
  {
    id: 'special-1',
    productId: 'lm-churros',
    discount: 15,
    badge: '15% OFF',
    validUntil: '2025-11-18',
  },
  {
    id: 'special-2',
    productId: 'mar-gansitos',
    discount: 20,
    badge: '20% OFF',
    validUntil: '2025-11-18',
  },
  {
    id: 'special-3',
    productId: 'jarritos',
    discount: 10,
    badge: 'PROMO',
    validUntil: '2025-11-18',
  },
];
