import { Product, Category } from '../types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Beverages' },
  { id: '2', name: 'Snacks' },
  { id: '3', name: 'Dairy' },
  { id: '4', name: 'Bakery' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Coca-Cola Classic 12oz Can',
    sku: 'COK-001',
    description: 'Classic Coca-Cola in 12oz cans',
    price: 24.99,
    cost: 18.00,
    margin: 28,
    imageUrl: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg',
    inStock: true,
    stock: 500,
    minStock: 100,
    supplier: 'Coca-Cola Co.',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#E31937',
    categoryId: '1',
  },
  {
    id: '2',
    name: 'Pepsi 12oz Can',
    sku: 'PEP-001',
    description: 'Pepsi Cola in 12oz cans',
    price: 23.99,
    cost: 17.50,
    margin: 27,
    imageUrl: 'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg',
    inStock: true,
    stock: 450,
    minStock: 100,
    supplier: 'PepsiCo',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#0051A5',
    categoryId: '1',
  },
  {
    id: '3',
    name: 'Lays Classic Chips',
    sku: 'LAY-001',
    description: 'Classic salted potato chips',
    price: 32.99,
    cost: 24.00,
    margin: 27,
    imageUrl: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg',
    inStock: true,
    stock: 300,
    minStock: 50,
    supplier: 'Frito-Lay',
    featured: true,
    unitType: 'case',
    unitsPerCase: 64,
    minOrderQty: 1,
    backgroundColor: '#FFC72C',
    categoryId: '2',
  },
  {
    id: '4',
    name: 'Doritos Nacho Cheese',
    sku: 'DOR-001',
    description: 'Nacho cheese flavored tortilla chips',
    price: 34.99,
    cost: 26.00,
    margin: 26,
    imageUrl: 'https://images.pexels.com/photos/1582692/pexels-photo-1582692.jpeg',
    inStock: true,
    stock: 280,
    minStock: 50,
    supplier: 'Frito-Lay',
    featured: false,
    unitType: 'case',
    unitsPerCase: 64,
    minOrderQty: 1,
    backgroundColor: '#FF0000',
    categoryId: '2',
  },
  {
    id: '5',
    name: 'Red Bull Energy Drink 8.4oz',
    sku: 'RDB-001',
    description: 'Energy drink with caffeine',
    price: 42.99,
    cost: 32.00,
    margin: 26,
    imageUrl: 'https://images.pexels.com/photos/2377045/pexels-photo-2377045.jpeg',
    inStock: true,
    stock: 200,
    minStock: 50,
    supplier: 'Red Bull GmbH',
    featured: true,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#1E3A8A',
    categoryId: '1',
  },
  {
    id: '6',
    name: 'Gatorade Lemon-Lime 20oz',
    sku: 'GAT-001',
    description: 'Sports drink with electrolytes',
    price: 28.99,
    cost: 21.00,
    margin: 28,
    imageUrl: 'https://images.pexels.com/photos/1346155/pexels-photo-1346155.jpeg',
    inStock: true,
    stock: 350,
    minStock: 75,
    supplier: 'PepsiCo',
    featured: false,
    unitType: 'case',
    unitsPerCase: 24,
    minOrderQty: 1,
    backgroundColor: '#00FF00',
    categoryId: '1',
  },
  {
    id: '7',
    name: 'Milk Whole Gallon',
    sku: 'MLK-001',
    description: 'Fresh whole milk',
    price: 48.99,
    cost: 38.00,
    margin: 22,
    imageUrl: 'https://images.pexels.com/photos/236010/pexels-photo-236010.jpeg',
    inStock: true,
    stock: 150,
    minStock: 30,
    supplier: 'Local Dairy',
    featured: false,
    unitType: 'case',
    unitsPerCase: 12,
    minOrderQty: 1,
    backgroundColor: '#FFFFFF',
    categoryId: '3',
  },
  {
    id: '8',
    name: 'Wonder Bread White',
    sku: 'WND-001',
    description: 'Classic white bread loaf',
    price: 38.99,
    cost: 28.00,
    margin: 28,
    imageUrl: 'https://images.pexels.com/photos/1775037/pexels-photo-1775037.jpeg',
    inStock: true,
    stock: 180,
    minStock: 40,
    supplier: 'Wonder Bakery',
    featured: false,
    unitType: 'case',
    unitsPerCase: 12,
    minOrderQty: 1,
    backgroundColor: '#FFE5B4',
    categoryId: '4',
  },
];

export const mockUser = {
  id: 'demo-user',
  email: 'demo@azteka.com',
  name: 'Demo User',
  role: 'ADMIN',
};
