"use strict";(()=>{var e={};e.id=7429,e.ids=[7429],e.modules={53524:e=>{e.exports=require("@prisma/client")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},91829:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>N,patchFetch:()=>v,requestAsyncStorage:()=>m,routeModule:()=>l,serverHooks:()=>O,staticGenerationAsyncStorage:()=>h});var s={};r.r(s),r.d(s,{GET:()=>p});var i=r(49303),o=r(88716),d=r(60670),a=r(87070),n=r(72331),u=r(55715);let c=e=>null==e?null:"number"==typeof e?Number.isFinite(e)?e:null:Number(e.toString());async function p(e,t){try{let e=t.params?.id;if(!e)throw new u.M(400,"Customer id is required");let r=await n.Z.customer.findUnique({where:{id:e},include:{priceOverrides:{include:{product:{select:{id:!0,name:!0,sku:!0,price:!0}}}}}});if(!r)throw new u.M(404,"Customer not found");let s=await n.Z.order.findMany({where:{customerId:e},orderBy:{createdAt:"desc"},take:5,include:{items:{include:{product:{select:{id:!0,name:!0,sku:!0}}}}}}),i=await n.Z.$queryRaw`
      SELECT b."id", b."name", COUNT(*)::int AS orders
      FROM "OrderItem" oi
      JOIN "Order" o ON o."id" = oi."orderId" AND o."customerId" = ${e}
      JOIN "Product" p ON p."id" = oi."productId"
      LEFT JOIN "Brand" b ON b."id" = p."brandId"
      WHERE b."id" IS NOT NULL
      GROUP BY b."id"
      ORDER BY orders DESC
      LIMIT 5
    `;return a.NextResponse.json({customer:{id:r.id,businessName:r.businessName,contactName:r.contactName,email:r.email,phone:r.phone,address:r.address,city:r.city,state:r.state,zipCode:r.zipCode,active:r.active},priceOverrides:r.priceOverrides.map(e=>({id:e.id,productId:e.productId,priceCase:e.priceCase,product:e.product?{id:e.product.id,name:e.product.name,sku:e.product.sku,listPrice:c(e.product.price)??0}:null})),recentOrders:s.map(e=>({id:e.id,total:e.total,createdAt:e.createdAt,itemCount:e.items.length})),preferredBrands:i})}catch(e){return(0,u.z)(e,"Failed to load customer profile")}}let l=new i.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/customers/[id]/route",pathname:"/api/customers/[id]",filename:"route",bundlePath:"app/api/customers/[id]/route"},resolvedPagePath:"/Users/ernestoponce/dev/azteka-dsd/app/api/customers/[id]/route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:m,staticGenerationAsyncStorage:h,serverHooks:O}=l,N="/api/customers/[id]/route";function v(){return(0,d.patchFetch)({serverHooks:O,staticGenerationAsyncStorage:h})}},55715:(e,t,r)=>{r.d(t,{M:()=>i,z:()=>o});var s=r(87070);class i extends Error{constructor(e,t,r){super(t),this.name="ApiError",this.status=e,this.details=r}toJSON(){return{error:this.message,...this.details?{details:this.details}:{}}}toResponse(){return s.NextResponse.json(this.toJSON(),{status:this.status})}}function o(e,t="Internal server error",r=500){return e instanceof i?e.toResponse():(console.error("[API ERROR]",e),s.NextResponse.json({error:t},{status:r}))}},72331:(e,t,r)=>{r.d(t,{Z:()=>i});var s=r(53524);let i=global.prisma??new s.PrismaClient}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[9276,5972],()=>r(91829));module.exports=s})();