DROP TABLE IF EXISTS "OrderItem" CASCADE;

DROP TABLE IF EXISTS "Order" CASCADE;

DROP TABLE IF EXISTS "CustomerPriceOverride" CASCADE;

DROP TABLE IF EXISTS "Product" CASCADE;

DROP TABLE IF EXISTS "Brand" CASCADE;

DROP TABLE IF EXISTS "Category" CASCADE;

DROP TABLE IF EXISTS "Customer" CASCADE;

DROP TABLE IF EXISTS "User" CASCADE;

